### ISSUE TITLE
Create dummy data for testing

### ISSUE THREAD

**Issue by daltonhahn** [KS-PACT/website#19]
Create 3 items of each table in the db for testing purposes

**Comment by jhauserw3241** [comment]
The base tests are here: 6e47f831c68ed83f9014205c0fc7c928a6c9d96e, 9b21abaf931b9a603ea9af43fd056f481fd197b1, ed6789be64327b088b7d27429b9711e10d3ce818, 06de4a0d758855713ec14c33346e88663d6c4246, d629f675a05d6396c035ba2470494dbe5b4dab23, 53e50eab51f3383e43af008532c9eb4339559df3, 23e6d056fec02602d9eedaf6eadd8538f1b652ed, 8e24851efb3709651f87dbf6c17fbdcf2159aeba

The test data for other edge cases will be added in a separate ticket.
